const CHANNELS = [
  { dial: 1, id: "", name: "Eventos", category: "Otros", logo: "https://infiniteott.github.io/logos/e/eventos.png" },
  { dial: 10, id: "Onetoro", name: "Toros TV", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/o/onetoro.png" },
  { dial: 12, id: "Hypermotion", name: "LaLiga Hypermotion", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/l/laliga-tv-hypermotion.png" },
  { dial: 16, id: "DSPORTS UY", name: "DSPORTS", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/d/directv-sports-color.png" },
  { dial: 17, id: "DSPORTS 2 UY", name: "DSPORTS 2", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/d/directv-sports-2-color.png" },
  { dial: 18, id: "DSPORTS Plus UY", name: "DSPORTS+", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/d/directv-sports-plus-color.png" },
  { dial: 21, id: "Setanta Sports LT", name: "Setanta Sports 1 (LT)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/s/setanta-sports-1.png" },
  { dial: 22, id: "Setanta Sports 2 LT", name: "Setanta Sports 2 (LT)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/s/setanta-sports-2.png" },
  { dial: 23, id: "beIN Sports 1 AU", name: "beIN Sports 1 (AU)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/b/bein-sports-1.png" },
  { dial: 24, id: "beIN Sports 2 AU", name: "beIN Sports 2 (AU)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/b/bein-sports-2.png" },
  { dial: 25, id: "beIN Sports 3 AU", name: "beIN Sports 3 (AU)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/b/bein-sports-3.png" },
  { dial: 26, id: "Premier Sports UK", name: "Premier Sports 1", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/p/premier-sports-1.png" },
  { dial: 27, id: "Premier Sports 2 UK", name: "Premier Sports 2", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/p/premier-sports-2.png" },
  { dial: 28, id: "", name: "Caze TV (BR)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/c/caze-tv.png" },
  { dial: 29, id: "", name: "Caze TV 2", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/c/caze-tv.png" },
  { dial: 31, id: "", name: "FanCode 1 (IN)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/f/fancode.png" },
  { dial: 32, id: "", name: "FanCode 2 (IN)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/f/fancode.png" },
  { dial: 41, id: "ESPN CL", name: "ESPN", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/e/espn.png" },
  { dial: 42, id: "ESPN 2 CL", name: "ESPN 2", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/e/espn-2.png" },
  { dial: 43, id: "ESPN 3 CL", name: "ESPN 3", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/e/espn-3.png" },
  { dial: 44, id: "ESPN 4 CL", name: "ESPN 4", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/e/espn-4.png" },
  { dial: 45, id: "ESPN 5 CL", name: "ESPN 5", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/e/espn-5.png" },
  { dial: 46, id: "ESPN 6 CL", name: "ESPN 6", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/e/espn-6.png" },
  { dial: 47, id: "ESPN 7 CL", name: "ESPN 7", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/e/espn-7.png" },
  { dial: 48, id: "ESPN Premium CL", name: "ESPN Premium", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/e/espn-premium.png" },
  { dial: 51, id: "Arena Sport 1 HR", name: "Arena Sport 1 (HR)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/a/arena-sport-1.png" },
  { dial: 52, id: "Arena Sport 2 HR", name: "Arena Sport 2 (HR)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/a/arena-sport-2.png" },
  { dial: 53, id: "Arena Sport 3 HR", name: "Arena Sport 3 (HR)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/a/arena-sport-3.png" },
  { dial: 54, id: "Arena Sport 4 HR", name: "Arena Sport 4 (HR)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/a/arena-sport-4.png" },
  { dial: 55, id: "Arena Sport 5 HR", name: "Arena Sport 5 (HR)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/a/arena-sport-5.png" },
  { dial: 56, id: "Arena Sport 6 HR", name: "Arena Sport 6 (HR)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/a/arena-sport-6.png" },
  { dial: 57, id: "Arena Sport 7 HR", name: "Arena Sport 7 (HR)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/a/arena-sport-7.png" },
  { dial: 58, id: "Arena Sport 8 HR", name: "Arena Sport 8 (HR)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/a/arena-sport-8.png" },
  { dial: 59, id: "Arena Sport 9 HR", name: "Arena Sport 9 (HR)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/a/arena-sport-9.png" },
  { dial: 60, id: "Arena Sport 10 HR", name: "Arena Sport 10 (HR)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/a/arena-sport-10.png" },
  { dial: 61, id: "Nova Sport 1 CZ", name: "Nova Sport 1", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/n/nova-sport-1.png" },
  { dial: 62, id: "Nova Sport 2 CZ", name: "Nova Sport 2", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/n/nova-sport-2.png" },
  { dial: 63, id: "", name: "CBS Sports Golazo", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/c/cbs-sports.png" },
  { dial: 66, id: "Go3 Sport Open LT", name: "Go3 Sport Open", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/g/go3-sport-open.png" },
  { dial: 69, id: "Polsat Sport 1", name: "Polsat Sport 1", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/p/polsat-sport-1.png" },
  { dial: 71, id: "TSN 1", name: "TSN 1", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/t/tsn-1.png" },
  { dial: 72, id: "TSN 2", name: "TSN 2", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/t/tsn-2.png" },
  { dial: 73, id: "TSN 3", name: "TSN 3", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/t/tsn-3.png" },
  { dial: 74, id: "TSN 4", name: "TSN 4", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/t/tsn-4.png" },
  { dial: 75, id: "TSN 5", name: "TSN 5", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/t/tsn-5.png" },
  { dial: 79, id: "SportDigital Fussball", name: "SportDigital Fussball", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/s/sportdigital-fussball.png" },
  { dial: 90, id: "", name: "Peacock > Premier League", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/p/premier-league-2.png" },
  { dial: 92, id: "sportv 2 BR", name: "sportv 2 (BR)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/s/sportv-2.png" },
  { dial: 93, id: "sportv 3 BR", name: "sportv 3 (BR)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/s/sportv-3.png" },
  { dial: 94, id: "RTBF Tipik", name: "Tipik > F1 & MotoGP", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/r/rtbf-tipik.png" },
  { dial: 96, id: "FOX Deportes", name: "FOX Deportes", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/f/fox-deportes.png" },
  { dial: 97, id: "FS1", name: "FS1", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/f/fs1.png" },
  { dial: 98, id: "FS2", name: "FS2", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/f/fs2.png" },
  { dial: 101, id: "Eurosport 1 ES", name: "Eurosport 1", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/e/eurosport-1.png" },
  { dial: 102, id: "Eurosport 2 ES", name: "Eurosport 2", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/e/eurosport-2.png" },
  { dial: 103, id: "Eurosport 1 SK", name: "Eurosport 1 (Europa del Este)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/e/eurosport-1.png" },
  { dial: 104, id: "Eurosport 2 SK", name: "Eurosport 2 (Europa del Este)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/e/eurosport-2.png" },
  { dial: 106, id: "Tennis Channel", name: "Tennis Channel", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/t/tennis-channel-iso.png" },
  { dial: 107, id: "", name: "Tennis Ch. 2", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/t/tennis-channel-2.png" },
  { dial: 108, id: "Sport1 SK", name: "Sport1 (SK)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/s/sport1.png" },
  { dial: 109, id: "Sport2 SK", name: "Sport2 (SK)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/s/sport2.png" },
  { dial: 110, id: "beIN Sports Xtra en espanol", name: "beIN Sports Xtra en espanol", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/b/bein-sports-xtra-en-espanol.png" },
  { dial: 111, id: "beIN Sports 1 FR", name: "beIN Sports 1 (FR)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/b/bein-sports-1.png" },
  { dial: 112, id: "beIN Sports 2 FR", name: "beIN Sports 2 (FR)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/b/bein-sports-2.png" },
  { dial: 113, id: "beIN Sports 3 FR", name: "beIN Sports 3 (FR)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/b/bein-sports-3.png" },
  { dial: 114, id: "beIN Sports 4 FR", name: "beIN Sports 4 (FR)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/b/bein-sports-4-max.png" },
  { dial: 115, id: "beIN Sports 5 FR", name: "beIN Sports 5 (FR)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/b/bein-sports-5-max.png" },
  { dial: 116, id: "beIN Sports 6 FR", name: "beIN Sports 6 (FR)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/b/bein-sports-6-max.png" },
  { dial: 117, id: "beIN Sports 7 FR", name: "beIN Sports 7 (FR)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/b/bein-sports-7-max.png" },
  { dial: 118, id: "beIN Sports 8 FR", name: "beIN Sports 8 (FR)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/b/bein-sports-8-max.png" },
  { dial: 119, id: "beIN Sports 9 FR", name: "beIN Sports 9 (FR)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/b/bein-sports-9-max.png" },
  { dial: 120, id: "beIN Sports 10 FR", name: "beIN Sports 10 (FR)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/b/bein-sports-10-max.png" },
  { dial: 121, id: "FOX MX", name: "FOX (MX)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/f/fox.png" },
  { dial: 122, id: "Fox Sports MX", name: "Fox Sports", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/f/fox-sports-mx.png" },
  { dial: 123, id: "Fox Sports 2 MX", name: "Fox Sports 2", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/f/fox-sports-2-mx.png" },
  { dial: 124, id: "Fox Sports 3 MX", name: "Fox Sports 3", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/f/fox-sports-3-mx.png" },
  { dial: 125, id: "Fox Sports Premium MX", name: "Fox Sports Premium", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/f/fox-sports-premium-mx.png" },
  { dial: 201, id: "Somos Cine", name: "Somos Cine > RTVE", category: "Cine", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/s/somos-cine.png" },
  { dial: 202, id: "Rakuten Cine Espanol", name: "Cine Espanol > Rakuten", category: "Cine", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/r/rakuten-cine-espanol.png" },
  { dial: 203, id: "8madrid TV", name: "8madrid TV", category: "Cine", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/0/8madrid-tv.png" },
  { dial: 208, id: "AXN", name: "AXN", category: "Cine", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/a/axn.png" },
  { dial: 209, id: "AXN Movies", name: "AXN Movies", category: "Cine", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/a/axn-movies.png" },
  { dial: 211, id: "Rakuten Pelis Top", name: "Pelis Top > Rakuten", category: "Cine", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/r/rakuten-pelis-top.png" },
  { dial: 212, id: "Pluto Cine Estelar", name: "Cine Estelar > Pluto", category: "Cine", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/p/pluto-cine-estelar.png" },
  { dial: 213, id: "Rakuten Accion", name: "Accion > Rakuten", category: "Cine", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/r/rakuten-accion.png" },
  { dial: 214, id: "Pluto Accion", name: "Accion > Pluto", category: "Cine", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/p/pluto-cine-accion.png" },
  { dial: 215, id: "Sony One Accion", name: "Sony One Accion", category: "Cine", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/s/sony-one-hits-accion.png" },
  { dial: 216, id: "Paramount Network de Pluto", name: "Paramount Network de Pluto", category: "Cine", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/p/paramount-network-de-pluto.png" },
  { dial: 217, id: "Pluto Sensacine TV", name: "Sensacine TV > Pluto", category: "Cine", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/p/pluto-sensacine-tv.png" },
  { dial: 218, id: "", name: "Moviesphere", category: "Cine", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/m/moviesphere.png" },
  { dial: 219, id: "", name: "LG 1 Film", category: "Cine", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/l/lg-1-film.png" },
  { dial: 221, id: "Rakuten Drama", name: "Drama > Rakuten", category: "Cine", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/r/rakuten-drama.png" },
  { dial: 222, id: "Pluto Drama", name: "Drama > Pluto", category: "Cine", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/p/pluto-cine-drama.png" },
  { dial: 223, id: "Rakuten Thrillers", name: "Thrillers > Rakuten", category: "Cine", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/r/rakuten-thrillers.png" },
  { dial: 224, id: "Pluto Thrillers", name: "Thrillers > Pluto", category: "Cine", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/p/pluto-thrillers.png" },
  { dial: 225, id: "Pluto Cine de autor", name: "Cine de autor > Pluto", category: "Cine", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/p/pluto-cine-de-autor.png" },
  { dial: 226, id: "Pluto Clasico", name: "Clasico > Pluto", category: "Cine", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/p/pluto-cine-clasico.png" },
  { dial: 228, id: "Pluto Western", name: "Western > Pluto", category: "Cine", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/p/pluto-western.png" },
  { dial: 231, id: "Rakuten Comedia", name: "Comedia > Rakuten", category: "Cine", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/r/rakuten-comedia.png" },
  { dial: 232, id: "Pluto Comedia", name: "Comedia > Pluto", category: "Cine", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/p/pluto-cine-comedia.png" },
  { dial: 233, id: "Pluto Comedia Made in Spain", name: "Comedia espanola > Pluto", category: "Cine", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/p/pluto-comedia-made-in-spain.png" },
  { dial: 234, id: "Sony One Comedia", name: "Sony One Comedia", category: "Cine", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/s/sony-one-hits-comedia.png" },
  { dial: 301, id: "", name: "Cocina Familiar", category: "Entretenimiento", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/c/cocina-familiar.png" },
  { dial: 302, id: "Pluto Cocina", name: "Pluto Cocina", category: "Entretenimiento", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/p/pluto-cocina.png" },
  { dial: 303, id: "Tastemade en espanol", name: "Tastemade en espanol", category: "Entretenimiento", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/t/tastemade.png" },
  { dial: 311, id: "El Mueble", name: "El Mueble", category: "Entretenimiento", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/e/el-mueble.png" },
  { dial: 312, id: "Pluto Diseno", name: "Pluto Diseno", category: "Entretenimiento", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/p/pluto-diseno.png" },
  { dial: 313, id: "Pluto Homeful", name: "Homeful > Pluto", category: "Entretenimiento", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/h/homeful.png" },
  { dial: 314, id: "Nesting TV", name: "Nesting TV", category: "Entretenimiento", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/n/nesting-tv.png" },
  { dial: 315, id: "The Design Network", name: "The Design Network", category: "Entretenimiento", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/t/the-design-network.png" },
  { dial: 321, id: "Ciudadanos por el mundo", name: "Ciudadanos por el mundo > Pluto", category: "Entretenimiento", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/c/ciudadanos-por-el-mundo.png" },
  { dial: 322, id: "DViaje", name: "DViaje", category: "Entretenimiento", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/d/dviaje.png" },
  { dial: 331, id: "Hola Play", name: "Hola Play", category: "Entretenimiento", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/h/hola-play.png" },
  { dial: 332, id: "En el punto de mira", name: "En el punto de mira", category: "Entretenimiento", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/e/en-el-punto-de-mira.png" },
  { dial: 333, id: "Equipo de investigacion", name: "Equipo de investigacion", category: "Entretenimiento", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/e/equipo-de-investigacion.png" },
  { dial: 334, id: "Wipeout", name: "Wipeout", category: "Entretenimiento", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/w/wipeout.png" },
  { dial: 335, id: "", name: "Just for Laughs", category: "Entretenimiento", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/j/just-for-laughs.png" },
  { dial: 401, id: "La 1", name: "La 1", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/l/la-1.png" },
  { dial: 401, id: "La 1 Catalunya", name: "La 1 Catalunya", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/l/la-1.png" },
  { dial: 401, id: "La 1 Canarias", name: "La 1 Canarias", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/l/la-1.png" },
  { dial: 402, id: "La 2", name: "La 2", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/l/la-2.png" },
  { dial: 402, id: "La 2 Cat", name: "La 2 Cat", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/l/la-2-cat.png" },
  { dial: 402, id: "La 2 Canarias", name: "La 2 Canarias", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/l/la-2.png" },
  { dial: 403, id: "", name: "Antena 3", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/a/antena-3.png" },
  { dial: 404, id: "", name: "Cuatro", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/c/cuatro.png" },
  { dial: 405, id: "", name: "Telecinco", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/t/telecinco.png" },
  { dial: 406, id: "", name: "laSexta", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/l/lasexta.png" },
  { dial: 407, id: "", name: "La Septima", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/l/la-septima.png" },
  { dial: 408, id: "Teledeporte", name: "Teledeporte", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/t/teledeporte.png" },
  { dial: 409, id: "Canal 24 Horas", name: "Canal 24 Horas", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/c/canal-24-horas.png" },
  { dial: 409, id: "Canal 24 Horas Catalunya", name: "C. 24H Catalunya", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/c/canal-24-horas.png" },
  { dial: 409, id: "Canal 24 Horas Canarias", name: "C. 24H Canarias", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/c/canal-24-horas.png" },
  { dial: 410, id: "Clan", name: "Clan", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/c/clan.png" },
  { dial: 411, id: "", name: "Deportes > RTVE Play 1", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/r/rtve-play.png" },
  { dial: 412, id: "", name: "Deportes > RTVE Play 2", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/r/rtve-play.png" },
  { dial: 413, id: "", name: "Deportes > RTVE Play 3", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/r/rtve-play.png" },
  { dial: 414, id: "", name: "Deportes > RTVE Play 4", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/r/rtve-play.png" },
  { dial: 415, id: "", name: "Deportes > RTVE Play 5", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/r/rtve-play.png" },
  { dial: 416, id: "", name: "Deportes > RTVE Play 6", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/r/rtve-play.png" },
  { dial: 417, id: "", name: "Deportes > RTVE Play 7", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/r/rtve-play.png" },
  { dial: 418, id: "", name: "Deportes > RTVE Play 8", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/r/rtve-play.png" },
  { dial: 419, id: "", name: "Deportes > RTVE Play 9", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/r/rtve-play.png" },
  { dial: 421, id: "", name: "Noticias > RTVE Play 1", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/r/rtve-play.png" },
  { dial: 422, id: "", name: "Noticias > RTVE Play 2", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/r/rtve-play.png" },
  { dial: 423, id: "", name: "Noticias > RTVE Play 3", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/r/rtve-play.png" },
  { dial: 424, id: "", name: "Noticias > RTVE Play 4", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/r/rtve-play.png" },
  { dial: 425, id: "", name: "Noticias > RTVE Play 5", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/r/rtve-play.png" },
  { dial: 426, id: "", name: "Noticias > RTVE Play 6", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/r/rtve-play.png" },
  { dial: 436, id: "TRECE", name: "TRECE", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/t/trece.png" },
  { dial: 437, id: "El Toro TV", name: "El Toro TV", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/e/el-toro-tv.png" },
  { dial: 438, id: "Distrito TV", name: "Distrito TV", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/d/distrito-tv.png" },
  { dial: 441, id: "Canal Parlamento", name: "Canal Parlamento", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/c/canal-parlamento.png" },
  { dial: 442, id: "", name: "Senado", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/s/senado.png" },
  { dial: 443, id: "Actualidad 360", name: "Actualidad 360", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/a/actualidad-360.png" },
  { dial: 444, id: "El Pais TV", name: "El Pais TV", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/e/el-pais.png" },
  { dial: 445, id: "El Confidencial", name: "El Confidencial TV", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/e/el-confidencial-tv.png" },
  { dial: 446, id: "Negocios TV", name: "Negocios TV", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/n/negocios-tv.png" },
  { dial: 447, id: "Euronews en espanol", name: "Euronews en espanol", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/e/euronews.png" },
  { dial: 448, id: "France24 en espanol", name: "France 24 en espanol", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/f/france24.png" },
  { dial: 449, id: "DW en espanol", name: "DW en espanol", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/d/deutsche-welle.png" },
  { dial: 450, id: "RT en espanol", name: "RT en espanol", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/r/russia-today.png" },
  { dial: 451, id: "CNN en espanol", name: "CNN en espanol", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/c/cnn-espanol.png" },
  { dial: 452, id: "CGTN Espanol", name: "CGTN Espanol", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/c/cgtn-espanol.png" },
  { dial: 453, id: "NHK World Espanol", name: "NHK World Espanol", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/n/nhk-world-japan.png" },
  { dial: 501, id: "ETB 1", name: "ETB 1", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/e/etb-1.png" },
  { dial: 502, id: "ETB 2", name: "ETB 2", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/e/etb-2.png" },
  { dial: 503, id: "ETB 1 On", name: "ETB 1 On", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/e/etb-1-on.png" },
  { dial: 504, id: "ETB 2 On", name: "ETB 2 On", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/e/etb-2-on.png" },
  { dial: 506, id: "TV3", name: "TV3", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/t/tv3.png" },
  { dial: 506, id: "TV3 CAT", name: "TV3 CAT", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/t/tv3-cat.png" },
  { dial: 507, id: "3cat Info", name: "3cat Info", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/0/3cat-info.png" },
  { dial: 508, id: "El 33", name: "33", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/0/33.png" },
  { dial: 509, id: "Super3", name: "Super3", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/s/super3.png" },
  { dial: 510, id: "Esport3", name: "Esport3", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/e/esport-3.png" },
  { dial: 511, id: "", name: "3cat Cameres", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/0/3cat.png" },
  { dial: 512, id: "", name: "3cat Exclusiu", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/0/3cat.png" },
  { dial: 516, id: "TVG", name: "TVG", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/t/tv-galicia.png" },
  { dial: 516, id: "TVG Europa", name: "TVG Europa", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/t/tv-galicia.png" },
  { dial: 517, id: "TVG 2", name: "TVG 2", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/t/tvg-2.png" },
  { dial: 521, id: "Canal Sur", name: "Canal Sur 1", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/c/canal-sur-1.png" },
  { dial: 521, id: "Canal Sur Andalucia", name: "Canal Sur Andalucia", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/c/canal-sur-andalucia.png" },
  { dial: 522, id: "Canal Sur", name: "Canal Sur 2", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/c/canal-sur-2.png" },
  { dial: 523, id: "Andalucia TV", name: "Andalucia TV", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/a/andalucia-tv.png" },
  { dial: 524, id: "", name: "Canal Sur Noticias", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/c/canal-sur-mas.png" },
  { dial: 526, id: "Telemadrid", name: "Telemadrid", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/t/telemadrid.png" },
  { dial: 527, id: "LaOtra", name: "LaOtra", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/l/la-otra.png" },
  { dial: 531, id: "A Punt", name: "A Punt", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/a/a-punt.png" },
  { dial: 531, id: "A Punt", name: "A Punt en linia", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/a/a-punt.png" },
  { dial: 532, id: "La 8 Mediterraneo", name: "La 8 Mediterraneo", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/l/la-8-mediterraneo.png" },
  { dial: 536, id: "TV Canaria", name: "TV Canaria", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/t/tv-canaria.png" },
  { dial: 536, id: "TV Canaria", name: "TV Canaria Net", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/t/tv-canaria.png" },
  { dial: 537, id: "", name: "Mirame TV", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/m/mirame-tv.png" },
  { dial: 538, id: "", name: "Atlantico Television", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/a/atlantico-television.png" },
  { dial: 541, id: "CMM TV", name: "CMM TV", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/c/cmm-color.png" },
  { dial: 541, id: "CMM TV", name: "CMM TV Global", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/c/cmm-color.png" },
  { dial: 542, id: "CMM TV", name: "CMM TV +2", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/c/cmm-color.png" },
  { dial: 546, id: "IB3 Global", name: "IB3 Global", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/i/ib3.png" },
  { dial: 551, id: "Canal Extremadura", name: "Canal Extremadura", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/c/canal-extremadura-color.png" },
  { dial: 551, id: "Canal Extremadura Sat", name: "Canal Extremadura Sat", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/c/canal-extremadura-sat.png" },
  { dial: 552, id: "Canal Extremadura Sat", name: "Canal Extremadura Sat +2", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/c/canal-extremadura-sat.png" },
  { dial: 556, id: "Aragon TV", name: "Aragon TV", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/a/aragon-tv.png" },
  { dial: 556, id: "Aragon TV Int", name: "Aragon TV Int", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/a/aragon-tv-int.png" },
  { dial: 561, id: "TPA 7", name: "TPA 7", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/t/tpa7.png" },
  { dial: 562, id: "TPA 8", name: "TPA 8", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/t/tpa8.png" },
  { dial: 564, id: "", name: "Cantabria TV", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/c/cantabria-tv.png" },
  { dial: 565, id: "Popular TV Cantabria", name: "Popular TV Cantabria", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/p/popular-tv.png" },
  { dial: 566, id: "7RM", name: "7RM", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/0/7rm.png" },
  { dial: 568, id: "", name: "Popular TV Murcia", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/p/popular-tv.png" },
  { dial: 571, id: "CyL 7", name: "CyL 7", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/c/cyl7.png" },
  { dial: 572, id: "La 8 Valladolid", name: "La 8 Valladolid", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/c/cyl8-valladolid.png" },
  { dial: 576, id: "Navarra Television", name: "Navarra Television", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/n/navarra-television.png" },
  { dial: 577, id: "Navarra Television 2", name: "Navarra Television 2", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/n/navarra-television-2.png" },
  { dial: 579, id: "TVR Rioja", name: "TVR", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/t/tvr-rioja.png" },
  { dial: 579, id: "TVR Rioja", name: "TVR Web", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/t/tvr-rioja.png" },
  { dial: 581, id: "", name: "RTVCE", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/r/rtvce.png" },
  { dial: 585, id: "", name: "Popular TV Melilla", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/p/popular-tv.png" },
  { dial: 586, id: "Bon Dia TV", name: "Bon Dia TV", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/b/bon-dia-tv-color.png" },
  { dial: 587, id: "Andorra Televisio", name: "Andorra Televisio", category: "Regionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/a/andorra-televisio.png" },
  { dial: 591, id: "", name: "Parlamento de Andalucia", category: "Regionales", logo: "///logosweb/p/parlamento-de-andalucia.png" },
  { dial: 592, id: "", name: "Corts Valencianes", category: "Regionales", logo: "///logosweb/c/corts-valencianes.png" },
  { dial: 593, id: "", name: "Junta de Castilla y Leon", category: "Regionales", logo: "///logosweb/j/junta-castilla-y-leon.png" },
  { dial: 594, id: "", name: "Parlamento de Navarra", category: "Regionales", logo: "///logosweb/p/parlamento-de-navarra.png" },
  { dial: 595, id: "", name: "Parlamento de La Rioja", category: "Regionales", logo: "///logosweb/p/parlamento-de-la-rioja.png" },
  { dial: "", id: "", name: "Cine navideno > Pluto", category: "Otros", logo: "" },
];
