const CHANNELS = [
  { dial: 0, id: "", name: "Canal 0", category: "Otros", logo: "" },
  { dial: 1, id: "", name: "Eventos", category: "Otros", logo: "https://infiniteott.github.io/logos/e/eventos.png" },
  { dial: 10, id: "Onetoro", name: "Toros TV", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/o/onetoro.png" },
  { dial: 12, id: "Hypermotion", name: "LaLiga Hypermotion", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/l/laliga-tv-hypermotion.png" },
  { dial: 16, id: "DSPORTS UY", name: "DSPORTS", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/d/directv-sports-color.png" },
  { dial: 17, id: "DSPORTS 2 UY", name: "DSPORTS 2", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/d/directv-sports-2-color.png" },
  { dial: 18, id: "DSPORTS Plus UY", name: "DSPORTS+", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/d/directv-sports-plus-color.png" },
  { dial: 21, id: "Setanta Sports LT", name: "Setanta Sports 1 (LT)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/s/setanta-sports-1.png" },
  { dial: 22, id: "Setanta Sports 2 LT", name: "Setanta Sports 2 (LT)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/s/setanta-sports-2.png" },
  { dial: 23, id: "beIN Sports 1 AU", name: "beIN Sports 1 (AU)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/b/bein-sports-1.png" },
  { dial: 24, id: "beIN Sports 2 AU", name: "beIN Sports 2 (AU)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/b/bein-sports-2.png" },
  { dial: 25, id: "beIN Sports 3 AU", name: "beIN Sports 3 (AU)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/b/bein-sports-3.png" },
  { dial: 26, id: "Premier Sports UK", name: "Premier Sports 1", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/p/premier-sports-1.png" },
  { dial: 27, id: "Premier Sports 2 UK", name: "Premier Sports 2", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/p/premier-sports-2.png" },
  { dial: 28, id: "", name: "Caze TV (BR)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/c/caze-tv.png" },
  { dial: 29, id: "", name: "Caze TV 2", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/c/caze-tv.png" },
  { dial: 31, id: "", name: "FanCode 1 (IN)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/f/fancode.png" },
  { dial: 32, id: "", name: "FanCode 2 (IN)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/f/fancode.png" },
  { dial: 41, id: "ESPN CL", name: "ESPN", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/e/espn.png" },
  { dial: 42, id: "ESPN 2 CL", name: "ESPN 2", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/e/espn-2.png" },
  { dial: 43, id: "ESPN 3 CL", name: "ESPN 3", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/e/espn-3.png" },
  { dial: 44, id: "ESPN 4 CL", name: "ESPN 4", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/e/espn-4.png" },
  { dial: 45, id: "ESPN 5 CL", name: "ESPN 5", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/e/espn-5.png" },
  { dial: 46, id: "ESPN 6 CL", name: "ESPN 6", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/e/espn-6.png" },
  { dial: 47, id: "ESPN 7 CL", name: "ESPN 7", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/e/espn-7.png" },
  { dial: 48, id: "ESPN Premium CL", name: "ESPN Premium", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/e/espn-premium.png" },
  { dial: 51, id: "Arena Sport 1 HR", name: "Arena Sport 1 (HR)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/a/arena-sport-1.png" },
  { dial: 52, id: "Arena Sport 2 HR", name: "Arena Sport 2 (HR)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/a/arena-sport-2.png" },
  { dial: 53, id: "Arena Sport 3 HR", name: "Arena Sport 3 (HR)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/a/arena-sport-3.png" },
  { dial: 54, id: "Arena Sport 4 HR", name: "Arena Sport 4 (HR)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/a/arena-sport-4.png" },
  { dial: 55, id: "Arena Sport 5 HR", name: "Arena Sport 5 (HR)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/a/arena-sport-5.png" },
  { dial: 56, id: "Arena Sport 6 HR", name: "Arena Sport 6 (HR)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/a/arena-sport-6.png" },
  { dial: 57, id: "Arena Sport 7 HR", name: "Arena Sport 7 (HR)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/a/arena-sport-7.png" },
  { dial: 58, id: "Arena Sport 8 HR", name: "Arena Sport 8 (HR)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/a/arena-sport-8.png" },
  { dial: 59, id: "Arena Sport 9 HR", name: "Arena Sport 9 (HR)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/a/arena-sport-9.png" },
  { dial: 60, id: "Arena Sport 10 HR", name: "Arena Sport 10 (HR)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/a/arena-sport-10.png" },
  { dial: 61, id: "Nova Sport 1 CZ", name: "Nova Sport 1", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/n/nova-sport-1.png" },
  { dial: 62, id: "Nova Sport 2 CZ", name: "Nova Sport 2", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/n/nova-sport-2.png" },
  { dial: 63, id: "", name: "CBS Sports Golazo", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/c/cbs-sports.png" },
  { dial: 66, id: "Go3 Sport Open LT", name: "Go3 Sport Open", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/g/go3-sport-open.png" },
  { dial: 69, id: "Polsat Sport 1", name: "Polsat Sport 1", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/p/polsat-sport-1.png" },
  { dial: 71, id: "TSN 1", name: "TSN 1", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/t/tsn-1.png" },
  { dial: 72, id: "TSN 2", name: "TSN 2", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/t/tsn-2.png" },
  { dial: 73, id: "TSN 3", name: "TSN 3", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/t/tsn-3.png" },
  { dial: 74, id: "TSN 4", name: "TSN 4", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/t/tsn-4.png" },
  { dial: 75, id: "TSN 5", name: "TSN 5", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/t/tsn-5.png" },
  { dial: 79, id: "SportDigital Fussball", name: "SportDigital Fussball", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/s/sportdigital-fussball.png" },
  { dial: 90, id: "", name: "Peacock > Premier League", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/p/premier-league-2.png" },
  { dial: 92, id: "sportv 2 BR", name: "sportv 2 (BR)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/s/sportv-2.png" },
  { dial: 93, id: "sportv 3 BR", name: "sportv 3 (BR)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/s/sportv-3.png" },
  { dial: 94, id: "RTBF Tipik", name: "Tipik > F1 & MotoGP", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/r/rtbf-tipik.png" },
  { dial: 96, id: "FOX Deportes", name: "FOX Deportes", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/f/fox-deportes.png" },
  { dial: 97, id: "FS1", name: "FS1", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/f/fs1.png" },
  { dial: 98, id: "FS2", name: "FS2", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/f/fs2.png" },
  { dial: 101, id: "Eurosport 1 ES", name: "Eurosport 1", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/e/eurosport-1.png" },
  { dial: 102, id: "Eurosport 2 ES", name: "Eurosport 2", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/e/eurosport-2.png" },
  { dial: 103, id: "Eurosport 1 SK", name: "Eurosport 1 (Europa del Este)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/e/eurosport-1.png" },
  { dial: 104, id: "Eurosport 2 SK", name: "Eurosport 2 (Europa del Este)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/e/eurosport-2.png" },
  { dial: 106, id: "Tennis Channel", name: "Tennis Channel", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/t/tennis-channel-iso.png" },
  { dial: 107, id: "", name: "Tennis Ch. 2", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/t/tennis-channel-2.png" },
  { dial: 108, id: "Sport1 SK", name: "Sport1 (SK)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/s/sport1.png" },
  { dial: 109, id: "Sport2 SK", name: "Sport2 (SK)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/s/sport2.png" },
  { dial: 110, id: "beIN Sports Xtra en espanol", name: "beIN Sports Xtra en espanol", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/b/bein-sports-xtra-en-espanol.png" },
  { dial: 111, id: "beIN Sports 1 FR", name: "beIN Sports 1 (FR)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/b/bein-sports-1.png" },
  { dial: 112, id: "beIN Sports 2 FR", name: "beIN Sports 2 (FR)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/b/bein-sports-2.png" },
  { dial: 113, id: "beIN Sports 3 FR", name: "beIN Sports 3 (FR)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/b/bein-sports-3.png" },
  { dial: 114, id: "beIN Sports 4 FR", name: "beIN Sports 4 (FR)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/b/bein-sports-4-max.png" },
  { dial: 115, id: "beIN Sports 5 FR", name: "beIN Sports 5 (FR)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/b/bein-sports-5-max.png" },
  { dial: 116, id: "beIN Sports 6 FR", name: "beIN Sports 6 (FR)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/b/bein-sports-6-max.png" },
  { dial: 117, id: "beIN Sports 7 FR", name: "beIN Sports 7 (FR)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/b/bein-sports-7-max.png" },
  { dial: 118, id: "beIN Sports 8 FR", name: "beIN Sports 8 (FR)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/b/bein-sports-8-max.png" },
  { dial: 119, id: "beIN Sports 9 FR", name: "beIN Sports 9 (FR)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/b/bein-sports-9-max.png" },
  { dial: 120, id: "beIN Sports 10 FR", name: "beIN Sports 10 (FR)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/b/bein-sports-10-max.png" },
  { dial: 121, id: "FOX MX", name: "FOX (MX)", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/f/fox.png" },
  { dial: 122, id: "Fox Sports MX", name: "Fox Sports", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/f/fox-sports-mx.png" },
  { dial: 123, id: "Fox Sports 2 MX", name: "Fox Sports 2", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/f/fox-sports-2-mx.png" },
  { dial: 124, id: "Fox Sports 3 MX", name: "Fox Sports 3", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/f/fox-sports-3-mx.png" },
  { dial: 125, id: "Fox Sports Premium MX", name: "Fox Sports Premium", category: "Deportes", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/f/fox-sports-premium-mx.png" },
  { dial: 201, id: "Somos Cine", name: "Somos Cine > RTVE", category: "Cine", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/s/somos-cine.png" },
  { dial: 202, id: "Rakuten Cine Espanol", name: "Cine Espanol > Rakuten", category: "Cine", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/r/rakuten-cine-espanol.png" },
  { dial: 203, id: "8madrid TV", name: "8madrid TV", category: "Cine", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/0/8madrid-tv.png" },
  { dial: 208, id: "AXN", name: "AXN", category: "Cine", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/a/axn.png" },
  { dial: 209, id: "AXN Movies", name: "AXN Movies", category: "Cine", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/a/axn-movies.png" },
  { dial: 211, id: "Rakuten Pelis Top", name: "Pelis Top > Rakuten", category: "Cine", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/r/rakuten-pelis-top.png" },
  { dial: 212, id: "Pluto Cine Estelar", name: "Cine Estelar > Pluto", category: "Cine", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/p/pluto-cine-estelar.png" },
  { dial: 213, id: "Rakuten Accion", name: "Accion > Rakuten", category: "Cine", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/r/rakuten-accion.png" },
  { dial: 214, id: "Pluto Accion", name: "Accion > Pluto", category: "Cine", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/p/pluto-cine-accion.png" },
  { dial: 215, id: "Sony One Accion", name: "Sony One Accion", category: "Cine", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/s/sony-one-hits-accion.png" },
  { dial: 216, id: "Paramount Network de Pluto", name: "Paramount Network de Pluto", category: "Cine", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/p/paramount-network-de-pluto.png" },
  { dial: 217, id: "Pluto Sensacine TV", name: "Sensacine TV > Pluto", category: "Cine", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/p/pluto-sensacine-tv.png" },
  { dial: 218, id: "", name: "Moviesphere", category: "Cine", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/m/moviesphere.png" },
  { dial: 219, id: "", name: "LG 1 Film", category: "Cine", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/l/lg-1-film.png" },
  { dial: 221, id: "Rakuten Drama", name: "Drama > Rakuten", category: "Cine", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/r/rakuten-drama.png" },
  { dial: 222, id: "Pluto Drama", name: "Drama > Pluto", category: "Cine", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/p/pluto-cine-drama.png" },
  { dial: 223, id: "Rakuten Thrillers", name: "Thrillers > Rakuten", category: "Cine", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/r/rakuten-thrillers.png" },
  { dial: 224, id: "Pluto Thrillers", name: "Thrillers > Pluto", category: "Cine", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/p/pluto-thrillers.png" },
  { dial: 225, id: "Pluto Cine de autor", name: "Cine de autor > Pluto", category: "Cine", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/p/pluto-cine-de-autor.png" },
  { dial: 226, id: "Pluto Clasico", name: "Clasico > Pluto", category: "Cine", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/p/pluto-cine-clasico.png" },
  { dial: 228, id: "Pluto Western", name: "Western > Pluto", category: "Cine", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/p/pluto-western.png" },
  { dial: 231, id: "Rakuten Comedia", name: "Comedia > Rakuten", category: "Cine", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/r/rakuten-comedia.png" },
  { dial: 232, id: "Pluto Comedia", name: "Comedia > Pluto", category: "Cine", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/p/pluto-cine-comedia.png" },
  { dial: 233, id: "Pluto Comedia Made in Spain", name: "Comedia espanola > Pluto", category: "Cine", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/p/pluto-comedia-made-in-spain.png" },
  { dial: 234, id: "Sony One Comedia", name: "Sony One Comedia", category: "Cine", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/s/sony-one-hits-comedia.png" },
  { dial: 301, id: "", name: "Cocina Familiar", category: "Entretenimiento", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/c/cocina-familiar.png" },
  { dial: 302, id: "", name: "Pluto Cocina", category: "Entretenimiento", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/p/pluto-cocina.png" },
  { dial: 303, id: "", name: "Tastemade en espanol", category: "Entretenimiento", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/t/tastemade.png" },
  { dial: 311, id: "", name: "El Mueble", category: "Entretenimiento", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/e/el-mueble.png" },
  { dial: 312, id: "", name: "Pluto Diseno", category: "Entretenimiento", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/p/pluto-diseno.png" },
  { dial: 313, id: "", name: "Homeful > Pluto", category: "Entretenimiento", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/h/homeful.png" },
  { dial: 314, id: "", name: "Nesting TV", category: "Entretenimiento", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/n/nesting-tv.png" },
  { dial: 315, id: "", name: "The Design Network", category: "Entretenimiento", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/t/the-design-network.png" },
  { dial: 321, id: "", name: "Ciudadanos por el mundo > Pluto", category: "Entretenimiento", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/c/ciudadanos-por-el-mundo.png" },
  { dial: 322, id: "", name: "DViaje", category: "Entretenimiento", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/d/dviaje.png" },
  { dial: 331, id: "", name: "Hola Play", category: "Entretenimiento", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/h/hola-play.png" },
  { dial: 332, id: "", name: "En el punto de mira", category: "Entretenimiento", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/e/en-el-punto-de-mira.png" },
  { dial: 333, id: "", name: "Equipo de investigacion", category: "Entretenimiento", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/e/equipo-de-investigacion.png" },
  { dial: 334, id: "", name: "Wipeout", category: "Entretenimiento", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/w/wipeout.png" },
  { dial: 335, id: "", name: "Just for Laughs", category: "Entretenimiento", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/j/just-for-laughs.png" },
  { dial: 401, id: "La 1", name: "La 1", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/l/la-1.png" },
  { dial: 401, id: "La 1 Catalunya", name: "La 1 Catalunya", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/l/la-1.png" },
  { dial: 401, id: "La 1 Canarias", name: "La 1 Canarias", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/l/la-1.png" },
  { dial: 402, id: "La 2", name: "La 2", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/l/la-2.png" },
  { dial: 402, id: "La 2 Cat", name: "La 2 Cat", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/l/la-2-cat.png" },
  { dial: 402, id: "La 2 Canarias", name: "La 2 Canarias", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/l/la-2.png" },
  { dial: 403, id: "", name: "Antena 3", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/a/antena-3.png" },
  { dial: 404, id: "", name: "Cuatro", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/c/cuatro.png" },
  { dial: 405, id: "", name: "Telecinco", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/t/telecinco.png" },
  { dial: 406, id: "", name: "laSexta", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/l/lasexta.png" },
  { dial: 407, id: "", name: "La Septima", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/l/la-septima.png" },
  { dial: 408, id: "Teledeporte", name: "Teledeporte", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/t/teledeporte.png" },
  { dial: 409, id: "Canal 24 Horas", name: "Canal 24 Horas", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/c/canal-24-horas.png" },
  { dial: 409, id: "Canal 24 Horas Catalunya", name: "C. 24H Catalunya", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/c/canal-24-horas.png" },
  { dial: 409, id: "Canal 24 Horas Canarias", name: "C. 24H Canarias", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/c/canal-24-horas.png" },
  { dial: 410, id: "Clan", name: "Clan", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/c/clan.png" },
  { dial: 411, id: "", name: "Deportes > RTVE Play 1", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/r/rtve-play.png" },
  { dial: 412, id: "", name: "Deportes > RTVE Play 2", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/r/rtve-play.png" },
  { dial: 413, id: "", name: "Deportes > RTVE Play 3", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/r/rtve-play.png" },
  { dial: 414, id: "", name: "Deportes > RTVE Play 4", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/r/rtve-play.png" },
  { dial: 415, id: "", name: "Deportes > RTVE Play 5", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/r/rtve-play.png" },
  { dial: 416, id: "", name: "Deportes > RTVE Play 6", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/r/rtve-play.png" },
  { dial: 417, id: "", name: "Deportes > RTVE Play 7", category: "Nacionales", logo: "https://raw.githubusercontent.com/infiniteott/logos/refs/heads/main/r/rtve-play.png" },
  { dial: "", id: "", name: "Cine navideno > Pluto", category: "Otros", logo: "" },
];
